sonar.projectName=EVACUA API
sonar.projectVersion=0.1.0
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=test
sonar.test.inclusions=test/**/*.test.js
sonar.exclusions=node_modules/**,coverage/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.qualitygate.wait=true
sonar.qualitygate.timeout=300
